language: r
fortran: false
pandoc: false
latex: false

matrix:
  include:
    - dist: xenial
    - dist: bionic
    - os: osx
      osx_image: xcode12.2

addons:
  apt:
    packages:
      - libapparmor-dev
