language: r
sudo: required
cache: packages

matrix:
  include:
    - dist: precise
    - dist: trusty
    - dist: xenial
      env: R_CODECOV=true

addons:
  apt:
    packages:
      - libapparmor-dev

r_github_packages:
  - jimhester/covr

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
