language: r
fortran: false
pandoc: false
latex: false

matrix:
  include:
    - dist: precise
    - dist: trusty
    - dist: xenial
      env: R_CODECOV=true
    - os: osx

addons:
  apt:
    packages:
      - libapparmor-dev
